# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/js/asyncjs.nim
# rdoccmd: -r:off
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim"
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim"
