# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/js/jsconsole.nim
# rdoccmd: -r:off
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jsconsole_examples_1.nim"
