# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/js/jsconsole.nim
# rdoccmd: 
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim"
