# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/js/jscore.nim
# rdoccmd: 
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jscore_examples_1.nim"
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jscore_examples_2.nim"
