# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/js/jscore.nim
# rdoccmd: -r:off
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jscore_examples_3.nim"
