# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim"
