# autogenerated by docgen
# source: /home/runner/work/Nim-compiler/Nim-compiler/lib/std/jsheaders.nim
# rdoccmd: -r:off
import "/home/runner/work/Nim-compiler/Nim-compiler/doc/html/nimcache/runnableExamples/jsheaders_examples_1.nim"
